### ISSUE TITLE
一部の環境で開発環境が立たない

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/booQ-UI#308]
多分昔のWindowsでユーザー名が全角だと起きそう
```
6:43:25 [vite] Internal server error: Failed to load url /@fs/UsersユウヤDocumentsworkspacooQ-UIode_modules.vite
                                                                                                                ue.d81a3c25.js (resolved id: /UsersユウヤDocumentsworkspacooQ-UIode_modules.vite
                                                                                                                                                                                                ue.d81a3c25.js). Does the 
file exist?
      at transformRequest (E:\Users\ユウヤ\Documents\workspace\booQ-UI\node_modules\vite\dist\node\chunks\dep-baca5bcc.js:59159:15)
6:43:25 [vite] Internal server error: Failed to load url /@fs/UsersユウヤDocumentsworkspacooQ-UIsrcouter/index.ts (resolved id: /UsersユウヤDocumentsworkspacooQ-UIsrcouter/index.ts). Does the file exist?
      at transformRequest (E:\Users\ユウヤ\Documents\workspace\booQ-UI\node_modules\vite\dist\node\chunks\dep-baca5bcc.js:59159:15)
6:43:25 [vite] Internal server error: Failed to load url /@fs/UsersユウヤDocumentsworkspacooQ-UIsrcstore/index.ts (resolved id: /UsersユウヤDocumentsworkspacooQ-UIsrcstore/index.ts). Does the file exist?
      at transformRequest (E:\Users\ユウヤ\Documents\workspace\booQ-UI\node_modules\vite\dist\node\chunks\dep-baca5bcc.js:59159:15)
6:43:25 [vite] Internal server error: Failed to load url /@fs/UsersユウヤDocumentsworkspacooQ-UIsrcApp.vue (resolved id: /UsersユウヤDocumentsworkspacooQ-UIsrcApp.vue). Does the file exist?
      at transformRequest (E:\Users\ユウヤ\Documents\workspace\booQ-UI\node_modules\vite\dist\node\chunks\dep-baca5bcc.js:59159:15)
6:43:25 [vite] Internal server error: Failed to load url /@fs/UsersユウヤDocumentsworkspacooQ-UIsrcindex.scss (resolved id: /UsersユウヤDocumentsworkspacooQ-UIsrcindex.scss). Does the file exist?
      at transformRequest (E:\Users\ユウヤ\Documents\workspace\booQ-UI\node_modules\vite\dist\node\chunks\dep-baca5bcc.js:59159:15)
```

**Comment by ryoha000** [comment]
ドライブ直下だと動いたからpathのパースに失敗してそう

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/booQ-UI/pull/311
これで試してみて

**Comment by ryoha000** [comment]
や～、ダメそう
あんま困ってないから別にいいんだけど

**Comment by sapphi-red** [comment]
issue建てて

**Comment by ryoha000** [comment]
viteにってこと？
viteに立ってるかどうか確認してないわ

**Comment by ryoha000** [comment]
これかな？
https://github.com/vitejs/vite/issues/1384

**Comment by sapphi-red** [comment]
それっぽそう

**Comment by sapphi-red** [comment]
そういえばこれって直ってたんだっけ @ryoha000

**Comment by ryoha000** [comment]
試してなかった
試す

**Comment by ryoha000** [comment]
動いたあああああああああ
